// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfUsqQn-6Nhw4s4wxwcc3hv1Ex-1RKJ6M',
    appId: '1:333510438076:web:f9d18ae6b5be946e7474b9',
    messagingSenderId: '333510438076',
    projectId: 'trspe-86989',
    databaseURL: 'https://trspe-86989-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'trspe-86989.firebaseapp.com',
    storageBucket: 'trspe-86989.appspot.com',
    measurementId: 'G-ZBYS66B0ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ-oNBBvmzUCD1wxBPTmdf-P4PN1qPMyM',
    appId: '1:333510438076:android:e7a91d515f32c01c7474b9',
    messagingSenderId: '333510438076',
    databaseURL: 'https://trspe-86989-default-rtdb.asia-southeast1.firebasedatabase.app/',
    projectId: 'trspe-86989',
    storageBucket: 'trspe-86989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqEmC4xsb2pSuyxzxReg7XPun7sO1WrZc',
    appId: '1:333510438076:ios:b5112306595af46f7474b9',
    messagingSenderId: '333510438076',
    projectId: 'trspe-86989',
    databaseURL: 'https://trspe-86989-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'trspe-86989.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqEmC4xsb2pSuyxzxReg7XPun7sO1WrZc',
    appId: '1:333510438076:ios:b5112306595af46f7474b9',
    messagingSenderId: '333510438076',
    databaseURL: 'https://trspe-86989-default-rtdb.asia-southeast1.firebasedatabase.app/',
    projectId: 'trspe-86989',
    storageBucket: 'trspe-86989.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
